/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Liveness check */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/ready": {
    /** Readiness check */
    get: {
      responses: {
        /** @description Ready */
        200: {
          content: never;
        };
      };
    };
  };
  "/v1/auth/login": {
    /** Create a session */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Session created */
        200: {
          content: {
            "application/json": components["schemas"]["LoginResponse"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/auth/refresh": {
    /** Refresh access token */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RefreshRequest"];
        };
      };
      responses: {
        /** @description Token refreshed */
        200: {
          content: {
            "application/json": components["schemas"]["LoginResponse"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/auth/logout": {
    /** Revoke current session */
    post: {
      responses: {
        /** @description Logged out */
        204: {
          content: never;
        };
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/auth/me": {
    /** Get current user */
    get: {
      responses: {
        /** @description Current user with memberships */
        200: {
          content: {
            "application/json": components["schemas"]["AuthMeResponse"];
          };
        };
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/salons/{salonId}": {
    /** Get salon */
    get: {
      parameters: {
        path: {
          salonId: components["parameters"]["SalonId"];
        };
      };
      responses: {
        /** @description Salon */
        200: {
          content: {
            "application/json": components["schemas"]["Salon"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
    /** Update salon */
    patch: {
      parameters: {
        path: {
          salonId: components["parameters"]["SalonId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SalonUpdate"];
        };
      };
      responses: {
        /** @description Updated salon */
        200: {
          content: {
            "application/json": components["schemas"]["Salon"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/salons/{salonId}/business-hours": {
    /** Get salon business hours */
    get: {
      parameters: {
        path: {
          salonId: components["parameters"]["SalonId"];
        };
      };
      responses: {
        /** @description Business hours */
        200: {
          content: {
            "application/json": components["schemas"]["BusinessHoursWeekly"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
    /** Replace salon business hours */
    put: {
      parameters: {
        path: {
          salonId: components["parameters"]["SalonId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BusinessHoursWeekly"];
        };
      };
      responses: {
        /** @description Updated business hours */
        200: {
          content: {
            "application/json": components["schemas"]["BusinessHoursWeekly"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/services": {
    /** List services */
    get: {
      responses: {
        /** @description Service list */
        200: {
          content: {
            "application/json": components["schemas"]["ServiceList"];
          };
        };
        401: components["responses"]["ErrorResponse"];
      };
    };
    /** Create service */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ServiceCreate"];
        };
      };
      responses: {
        /** @description Created service */
        201: {
          content: {
            "application/json": components["schemas"]["Service"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/services/{serviceId}": {
    /** Get service */
    get: {
      parameters: {
        path: {
          serviceId: components["parameters"]["ServiceId"];
        };
      };
      responses: {
        /** @description Service */
        200: {
          content: {
            "application/json": components["schemas"]["Service"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
    /** Update service */
    patch: {
      parameters: {
        path: {
          serviceId: components["parameters"]["ServiceId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ServiceUpdate"];
        };
      };
      responses: {
        /** @description Updated service */
        200: {
          content: {
            "application/json": components["schemas"]["Service"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/staff": {
    /** List staff */
    get: {
      responses: {
        /** @description Staff list */
        200: {
          content: {
            "application/json": components["schemas"]["StaffList"];
          };
        };
        401: components["responses"]["ErrorResponse"];
      };
    };
    /** Create staff */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["StaffCreate"];
        };
      };
      responses: {
        /** @description Created staff */
        201: {
          content: {
            "application/json": components["schemas"]["Staff"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/staff/{staffId}": {
    /** Update staff */
    patch: {
      parameters: {
        path: {
          staffId: components["parameters"]["StaffId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StaffUpdate"];
        };
      };
      responses: {
        /** @description Updated staff */
        200: {
          content: {
            "application/json": components["schemas"]["Staff"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/staff/{staffId}/time-off": {
    /** List staff time off entries */
    get: {
      parameters: {
        path: {
          staffId: components["parameters"]["StaffId"];
        };
      };
      responses: {
        /** @description Time off list */
        200: {
          content: {
            "application/json": components["schemas"]["StaffTimeOffList"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
    /** Create staff time off */
    post: {
      parameters: {
        path: {
          staffId: components["parameters"]["StaffId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StaffTimeOffCreate"];
        };
      };
      responses: {
        /** @description Time off entry created */
        201: {
          content: {
            "application/json": components["schemas"]["StaffTimeOff"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/staff/{staffId}/time-off/{timeOffId}": {
    /** Delete staff time off entry */
    delete: {
      parameters: {
        path: {
          staffId: components["parameters"]["StaffId"];
          timeOffId: string;
        };
      };
      responses: {
        /** @description Deleted */
        204: {
          content: never;
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/staff/{staffId}/services": {
    /** List services assigned to staff */
    get: {
      parameters: {
        path: {
          staffId: components["parameters"]["StaffId"];
        };
      };
      responses: {
        /** @description Staff services */
        200: {
          content: {
            "application/json": components["schemas"]["StaffServicesResponse"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
    /** Assign services to staff */
    post: {
      parameters: {
        path: {
          staffId: components["parameters"]["StaffId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StaffServicesAssignRequest"];
        };
      };
      responses: {
        /** @description Assigned services */
        200: {
          content: {
            "application/json": components["schemas"]["StaffServicesResponse"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/customers": {
    /** List customers */
    get: {
      parameters: {
        query?: {
          page?: components["parameters"]["Page"];
          limit?: components["parameters"]["Limit"];
        };
      };
      responses: {
        /** @description Customer list */
        200: {
          content: {
            "application/json": components["schemas"]["CustomerList"];
          };
        };
        401: components["responses"]["ErrorResponse"];
      };
    };
    /** Create customer */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CustomerCreate"];
        };
      };
      responses: {
        /** @description Created customer */
        201: {
          content: {
            "application/json": components["schemas"]["Customer"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/customers/{customerId}": {
    /** Get customer */
    get: {
      parameters: {
        path: {
          customerId: components["parameters"]["CustomerId"];
        };
      };
      responses: {
        /** @description Customer */
        200: {
          content: {
            "application/json": components["schemas"]["Customer"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
    /** Update customer */
    patch: {
      parameters: {
        path: {
          customerId: components["parameters"]["CustomerId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CustomerUpdate"];
        };
      };
      responses: {
        /** @description Updated customer */
        200: {
          content: {
            "application/json": components["schemas"]["Customer"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/availability/slots": {
    /** List available booking slots */
    get: {
      parameters: {
        query: {
          serviceId: string;
          from?: string;
          days?: number;
          limit?: number;
          staffId?: string;
          intervalMinutes?: number;
        };
      };
      responses: {
        /** @description Available slots */
        200: {
          content: {
            "application/json": components["schemas"]["AvailabilityResponse"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/bookings": {
    /** List bookings */
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          status?: "pending" | "confirmed" | "in_progress" | "completed" | "cancelled" | "no_show";
        };
        path: {
          staffId: components["parameters"]["StaffId"];
        };
      };
      responses: {
        /** @description Booking list */
        200: {
          content: {
            "application/json": components["schemas"]["BookingList"];
          };
        };
        401: components["responses"]["ErrorResponse"];
      };
    };
    /** Create booking */
    post: {
      parameters: {
        header?: {
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BookingCreate"];
        };
      };
      responses: {
        /** @description Created booking */
        201: {
          content: {
            "application/json": components["schemas"]["Booking"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/bookings/{bookingId}": {
    /** Get booking */
    get: {
      parameters: {
        path: {
          bookingId: components["parameters"]["BookingId"];
        };
      };
      responses: {
        /** @description Booking */
        200: {
          content: {
            "application/json": components["schemas"]["Booking"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
    /** Update booking */
    patch: {
      parameters: {
        path: {
          bookingId: components["parameters"]["BookingId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BookingUpdate"];
        };
      };
      responses: {
        /** @description Updated booking */
        200: {
          content: {
            "application/json": components["schemas"]["Booking"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/bookings/{bookingId}/checkout": {
    /** Create online checkout session for booking */
    post: {
      parameters: {
        header?: {
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path: {
          bookingId: components["parameters"]["BookingId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BookingCheckoutRequest"];
        };
      };
      responses: {
        /** @description Checkout session created */
        201: {
          content: {
            "application/json": components["schemas"]["BookingCheckoutResponse"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/bookings/{bookingId}/cancel": {
    /** Cancel a booking */
    post: {
      parameters: {
        path: {
          bookingId: components["parameters"]["BookingId"];
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CancelBookingRequest"];
        };
      };
      responses: {
        /** @description Cancelled booking */
        200: {
          content: {
            "application/json": components["schemas"]["BookingResponse"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/bookings/{bookingId}/reschedule": {
    /** Reschedule a booking */
    post: {
      parameters: {
        path: {
          bookingId: components["parameters"]["BookingId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RescheduleBookingRequest"];
        };
      };
      responses: {
        /** @description Rescheduled booking */
        200: {
          content: {
            "application/json": components["schemas"]["BookingResponse"];
          };
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/payments/{paymentId}": {
    /** Get payment */
    get: {
      parameters: {
        path: {
          paymentId: components["parameters"]["PaymentId"];
        };
      };
      responses: {
        /** @description Payment */
        200: {
          content: {
            "application/json": components["schemas"]["Payment"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        404: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/webhooks/stripe": {
    /** Stripe webhook receiver */
    post: {
      parameters: {
        header: {
          "stripe-signature": string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StripeWebhookEvent"];
        };
      };
      responses: {
        /** @description Webhook received */
        200: {
          content: never;
        };
        400: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/notifications/send": {
    /** Send notification */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["NotificationRequest"];
        };
      };
      responses: {
        /** @description Notification queued */
        202: {
          content: never;
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/notifications/outbox": {
    /** List notification outbox entries */
    get: {
      parameters: {
        query?: {
          status?: "pending" | "processing" | "sent" | "failed";
          limit?: number;
        };
      };
      responses: {
        /** @description Outbox entries */
        200: {
          content: {
            "application/json": components["schemas"]["OutboxListResponse"];
          };
        };
        401: components["responses"]["ErrorResponse"];
        403: components["responses"]["ErrorResponse"];
      };
    };
  };
  "/v1/devices/register": {
    /** Register device for push notifications */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["DeviceRegisterRequest"];
        };
      };
      responses: {
        /** @description Device registered */
        201: {
          content: never;
        };
        400: components["responses"]["ErrorResponse"];
        401: components["responses"]["ErrorResponse"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Error: {
      code: string;
      message: string;
      errorKey: string;
      messageKey: string;
      details?: {
        [key: string]: unknown;
      };
      traceId: string;
    };
    User: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "owner" | "admin" | "staff";
      /** Format: uuid */
      salonId?: string;
    };
    AuthUser: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email?: string;
      fullName?: string;
      phone?: string;
      /** Format: uuid */
      primarySalonId?: string;
    };
    AuthSalonSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      status?: "draft" | "active";
      locale: string;
      currency: string;
      timezone: string;
    };
    Membership: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      salonId: string;
      /** @enum {string} */
      role: "owner" | "admin" | "staff";
      active: boolean;
      salon?: components["schemas"]["AuthSalonSummary"];
    };
    AuthMeResponse: {
      user: components["schemas"]["AuthUser"];
      memberships: components["schemas"]["Membership"][];
      /** Format: uuid */
      primarySalonId?: string;
      salon?: components["schemas"]["AuthSalonSummary"];
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      deviceId?: string;
    };
    RefreshRequest: {
      refreshToken: string;
    };
    LoginResponse: {
      accessToken: string;
      refreshToken: string;
      expiresIn: number;
      user: components["schemas"]["User"];
    };
    Salon: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      status?: "draft" | "active";
      currency?: string;
      locale?: string;
      timezone?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    SalonUpdate: {
      name?: string;
      currency?: string;
      locale?: string;
      timezone?: string;
    };
    BusinessHoursDay: {
      /** @enum {string} */
      day: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
      /** @example 09:00 */
      startTime: string;
      /** @example 17:00 */
      endTime: string;
      enabled: boolean;
    };
    BusinessHoursWeekly: {
      weekly: components["schemas"]["BusinessHoursDay"][];
    };
    SalonCreate: {
      name: string;
      currency: string;
      locale: string;
      timezone: string;
    };
    Service: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      salonId: string;
      name: string;
      /** @description Minor units (e.g., øre) */
      price: number;
      currency: string;
      durationMinutes: number;
      bufferMinutes?: number;
      active?: boolean;
    };
    ServiceCreate: {
      name: string;
      /** @description Minor units (e.g., øre) */
      price: number;
      currency: string;
      durationMinutes: number;
      bufferMinutes?: number;
      active?: boolean;
    };
    ServiceUpdate: {
      name?: string;
      /** @description Minor units (e.g., øre) */
      price?: number;
      currency?: string;
      durationMinutes?: number;
      bufferMinutes?: number;
      active?: boolean;
    };
    ServiceList: {
      data: components["schemas"]["Service"][];
    };
    Staff: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      salonId: string;
      name: string;
      /** @enum {string} */
      role: "owner" | "admin" | "staff";
      active?: boolean;
    };
    StaffCreate: {
      name: string;
      /** @enum {string} */
      role: "owner" | "admin" | "staff";
      active?: boolean;
    };
    StaffUpdate: {
      name?: string;
      /** @enum {string} */
      role?: "owner" | "admin" | "staff";
      active?: boolean;
      email?: string;
      phone?: string;
    };
    StaffServicesAssignRequest: {
      serviceIds: string[];
    };
    StaffServicesResponse: {
      /** Format: uuid */
      staffId: string;
      serviceIds: string[];
    };
    StaffList: {
      data: components["schemas"]["Staff"][];
    };
    StaffTimeOff: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      salonId: string;
      /** Format: uuid */
      staffId: string;
      /** Format: date-time */
      startTime: string;
      /** Format: date-time */
      endTime: string;
      reason?: string;
    };
    StaffTimeOffCreate: {
      /** Format: date-time */
      startUtc: string;
      /** Format: date-time */
      endUtc: string;
      reason?: string;
    };
    StaffTimeOffList: {
      data: components["schemas"]["StaffTimeOff"][];
    };
    Customer: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: email */
      email?: string;
      phone?: string;
      notes?: string;
    };
    CustomerCreate: {
      name: string;
      /** Format: email */
      email?: string;
      phone?: string;
      notes?: string;
    };
    CustomerUpdate: {
      name?: string;
      /** Format: email */
      email?: string;
      phone?: string;
      notes?: string;
    };
    CustomerList: {
      data: components["schemas"]["Customer"][];
    };
    AvailabilitySlot: {
      /** Format: date-time */
      startUtc: string;
      /** Format: date-time */
      endUtc: string;
      /** Format: uuid */
      staffId: string;
    };
    AvailabilityMeta: {
      /** Format: date-time */
      fromUtc: string;
      days: number;
      intervalMinutes: number;
      /** Format: uuid */
      serviceId: string;
      /** Format: uuid */
      staffId?: string;
      timezone: string;
    };
    AvailabilityResponse: {
      slots: components["schemas"]["AvailabilitySlot"][];
      meta: components["schemas"]["AvailabilityMeta"];
    };
    Booking: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      salonId: string;
      /** Format: uuid */
      customerId: string;
      /** Format: uuid */
      staffId: string;
      /** Format: uuid */
      serviceId: string;
      /**
       * Format: date-time
       * @description UTC ISO timestamp
       */
      startTime: string;
      /**
       * Format: date-time
       * @description UTC ISO timestamp
       */
      endTime: string;
      /** @enum {string} */
      status: "pending" | "confirmed" | "in_progress" | "completed" | "cancelled" | "no_show";
      /** @description Minor units (e.g., øre) */
      totalAmount: number;
      currency: string;
      notes?: string;
      customerName?: string;
      staffName?: string;
      serviceName?: string;
      /** @enum {string} */
      paymentStatus?: "pending" | "paid" | "failed" | "refunded";
      /** Format: uuid */
      paymentId?: string;
    };
    BookingCreate: {
      /** Format: uuid */
      customerId?: string;
      customer?: components["schemas"]["CustomerCreate"];
      /** Format: uuid */
      staffId: string;
      /** Format: uuid */
      serviceId: string;
      /**
       * Format: date-time
       * @description UTC ISO timestamp, must align to 15-minute grid.
       */
      startUtc: string;
      /**
       * Format: date-time
       * @description Optional; server computes endTime based on service duration.
       */
      endUtc?: string;
      /**
       * Format: date-time
       * @description Deprecated alias for startUtc.
       */
      startTime?: string;
      /**
       * Format: date-time
       * @description Deprecated alias for endUtc.
       */
      endTime?: string;
      notes?: string;
    };
    BookingResponse: {
      booking: components["schemas"]["Booking"];
    };
    CancelBookingRequest: {
      reasonKey?: string;
      note?: string;
    };
    RescheduleBookingRequest: {
      /** Format: uuid */
      staffId: string;
      /**
       * Format: date-time
       * @description UTC ISO timestamp, must align to 15-minute grid.
       */
      startUtc: string;
    };
    BookingUpdate: {
      /** Format: date-time */
      startTime?: string;
      /** Format: date-time */
      endTime?: string;
      /** @enum {string} */
      status?: "pending" | "confirmed" | "in_progress" | "completed" | "cancelled" | "no_show";
      notes?: string;
    };
    BookingList: {
      data: components["schemas"]["Booking"][];
    };
    BookingCheckoutRequest: {
      /** @enum {string} */
      provider?: "stripe" | "mobilepay";
      /** Format: uri */
      successUrl: string;
      /** Format: uri */
      cancelUrl: string;
      /** @description Optional idempotency key for checkout creation. */
      idempotencyKey?: string;
    };
    BookingCheckoutResponse: {
      /** Format: uri */
      checkoutUrl: string;
      /** Format: uuid */
      paymentId: string;
      /** @enum {string} */
      provider: "stripe" | "mobilepay";
    };
    Payment: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      bookingId: string;
      /** @enum {string} */
      status: "pending" | "paid" | "failed" | "refunded";
      /** @description Minor units (e.g., øre) */
      amount: number;
      currency: string;
      /** @enum {string} */
      provider: "stripe" | "mobilepay";
      providerReference?: string;
    };
    /** @description Raw Stripe webhook payload. Schema is intentionally minimal for forward compatibility. */
    StripeWebhookEvent: {
      id?: string;
      type?: string;
      data?: {
        object?: Record<string, never>;
      };
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    NotificationRequest: {
      /** @enum {string} */
      type: "email" | "sms" | "push";
      to: string;
      template: string;
      data?: {
        [key: string]: unknown;
      };
    };
    OutboxEntry: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      salonId: string;
      /** Format: uuid */
      bookingId?: string | null;
      type: string;
      /** @enum {string} */
      channel: "email" | "sms" | "push";
      provider: string;
      recipient: string;
      payload: {
        [key: string]: unknown;
      };
      /** @enum {string} */
      status: "pending" | "processing" | "sent" | "failed";
      dedupeKey?: string | null;
      attempts: number;
      /** Format: date-time */
      nextAttemptAt?: string | null;
      /** Format: date-time */
      lockedAt?: string | null;
      lockedBy?: string | null;
    };
    OutboxListResponse: {
      entries: components["schemas"]["OutboxEntry"][];
    };
    DeviceRegisterRequest: {
      deviceId: string;
      /** @enum {string} */
      platform: "ios" | "android" | "web";
      pushToken: string;
    };
  };
  responses: {
    /** @description Error response */
    ErrorResponse: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    Page?: number;
    Limit?: number;
    SalonId: string;
    ServiceId: string;
    StaffId: string;
    CustomerId: string;
    BookingId: string;
    PaymentId: string;
    /** @description Optional idempotency key to safely retry creates. */
    IdempotencyKey?: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
